apiVersion: apps/v1
kind: Deployment

metadata:
  name: protected-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: protected-api

  template:
    metadata:
      labels:
        app: protected-api

    spec:
      # Este Pod usará la identidad "protected-api".
      #
      # Kubernetes montará automáticamente su token en:
      # /var/run/secrets/kubernetes.io/serviceaccount/token
      serviceAccountName: protected-api

      containers:
        - name: protected-api
          image: protected-api:latest

          # Se usa la imagen cargada previamente dentro de Kind.
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000